name: Coding Standards

on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "**.php"
      - "**.phtml"

jobs:
  phpcs:
    name: "Coding Standards"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "8.1"

    env:
      PHP_VERSION_CODE_QUALITY: ${{ secrets.PHP_VERSION_CODE_QUALITY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: Install Rezolve Coding Standard
        run: git clone https://github.com/rezolved/rezolve_rce_coding_standard.git && cd rezolve_rce_coding_standard && composer install && cd ..

      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Run Rector
        id: rectorCheck
        continue-on-error: true
        run: cp -r rezolve_rce_coding_standard/src/rector.php rector.php && rezolve_rce_coding_standard/vendor/bin/rector process --ansi --no-progress-bar --dry-run ${{ steps.files.outputs.added_modified }}

      - name: Run Phpcs
        id: phpcsCheck
        uses: tinovyatkin/action-php-codesniffer@v1
        with:
          files: "**"
          scope: files
          phpcs_path: rezolve_rce_coding_standard/vendor/bin/phpcs --ignore=rezolve_rce_coding_standard/ --runtime-set ignore_warnings_on_exit 1
          standard: rezolve_rce_coding_standard/src/ruleset.xml
