name: Coding Standards

on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "**.php"
      - "**.phtml"

jobs:
  strategy:
    matrix:
      php-version:
        - "8.1"

  phpcs:
    runs-on: ubuntu-latest
    env:
      PHP_VERSION_CODE_QUALITY: ${{ secrets.PHP_VERSION_CODE_QUALITY }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Set up PHP"
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          tools: composer:v2

      - name: "Install locked dependencies with composer"
        run: "composer install --ansi --no-interaction --no-progress"

      - id: files
        uses: jitterbit/get-changed-files@v1